### PR TITLE
fix: wire differential tests into lib.rs and fix compilation errors (…

### PR DESCRIPTION
**Pull request by soyaya**
…#226)

- Add set_native_asset_address entrypoint to lib.rs (required by test harness)
- Declare diff_harness, differential_test, migration_verification_test modules in lib.rs via #[path] so they compile independently of broken sibling modules
- Add missing Ledger trait import in differential_test.rs and migration_verification_test.rs for set_timestamp calls
- All 9 tests now pass: 6 differential + 3 migration verification

## What Changed

Summarize the main code and behavior changes.

## Why

Explain the problem this PR solves.

## Testing

- [ ] Unit tests updated or added
- [ ] Relevant local checks passed
- [ ] Manual verification completed when needed

## Related Issues

Link the related issue(s), for example: Closes #123

### CODE REVIEW

**Comment by soyaya** [comment]
close #280

**Comment by Smartdevs17** [comment]
⚠️ Cannot merge

Hi @soyaya,

This PR could not be merged. Please check for conflicts and resolve them.

---
*🤖 Drips Wave Review Agent*
